beer = Category.create(name: "Beer", alc_percent: 6)
tequila = Category.create(name: "Tequila", alc_percent: 40)
vodka = Category.create(name: "Vodka", alc_percent: 40)
brandy = Category.create(name: "Brandy", alc_percent: 40)
rum = Category.create(name: "Rum", alc_percent: 60)
whisky = Category.create(name: "Whisky", alc_percent: 40)
red_wine = Category.create(name: "Red Wine", alc_percent: 13)
white_wine = Category.create(name: "White Wine", alc_percent: 13)

Drink.create("Miller Genuine Draft", category: beer, alc_percent: 5, serving: 340, serving_type: "Bottle")
Drink.create("Amstel Light", category: beer, alc_percent: 3.5, serving: 340, serving_type: "Bottle")
Drink.create("Budweiser", category: beer, alc_percent: 5, serving: 340, serving_type: "Bottle")
Drink.create("Coors Light", category: beer, alc_percent: 4.2, serving: 340, serving_type: "Bottle")
Drink.create("Corona Extra", category: beer, alc_percent: 4.6, serving: 340, serving_type: "Bottle")
Drink.create("San Miguel Premium All-Malt", category: beer, alc_percent: 5, serving: 340, serving_type: "Bottle")
Drink.create("San Miguel Pale Pilsen", category: beer, alc_percent: 5, serving: 340, serving_type: "Bottle")
Drink.create("San Mig Light", category: beer, alc_percent: 5, serving: 340, serving_type: "Bottle")
Drink.create("Red Horse Extra Strong", category: beer, alc_percent: 6.9, serving: 340, serving_type: "Bottle")
Drink.create("San Miguel Super Dry", category: beer, alc_percent: 4.8, serving: 340, serving_type: "Bottle")
Drink.create("1800 Silver (Blanco)", category: tequila , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("1800 Select Silver", category: tequila , alc_percent:  50 , serving: 44 , serving_type: "Shot")
Drink.create("Jose Cuervo Gold", category: tequila , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Jose Cuervo Sliver", category: tequila , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Tequila Rose", category: tequila , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Absolut Vodka", category: vodka , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Stolichnaya Vodka", category: vodka , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Smirnoff", category: vodka , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Grey Goose", category: vodka , alc_percent:  40 , serving: 44 , serving_type: "Shot")
Drink.create("Fundador", category: brandy, alc_percent: 40 , serving: 44 , serving_type: "Shot")
Drink.create("Remy Martin", category: brandy, alc_percent: 40 , serving: 44 , serving_type: "Shot")

